### PR TITLE
fix: remove background fix position

### PR DESCRIPTION
**Pull request by vidaaudrey**
Wrapper with fixed position will prevent the component area of storybook from scrolling down.

### CODE REVIEW

**Comment by johnthepink** [comment]
@vidaaudrey thanks for the PR! We will get this reviewed soon.

**Comment by jbaxleyiii** [comment]
@vidaaudrey if we remove `position: fixed` then the background doesn't take up the entire container. We should improve support for scrolling contents however.

Would you be able to adjust this PR to allow the background to still cover the entire preview and allow for scrolling?

I'd be happy to help if you need any guidance!

**Comment by vidaaudrey** [comment]
Hi @jbaxleyiii  sorry for my late reply. I'm not sure what's the best way to fix the problem. Could you let me know? Thanks.

**Comment by jbaxleyiii** [comment]
@vidaaudrey I think https://github.com/NewSpring/react-storybook-addon-backgrounds/pull/17 will actually fix the issue! I'm going to release it today so we can see!

**Pull request closed without merging**
