### PR TITLE
Fixes HMR when used as a global decorator

### PR DESCRIPTION
**Pull request by Coobaha**

### CODE REVIEW

**Comment by johnthepink** [comment]
@Coobaha thanks so much! We would love to get a test added for this case. Is that something you could do? 😸

**Comment by Coobaha** [comment]
@johnthepink 👍

**Comment by jbaxleyiii** [comment]
@Coobaha awesome! I'll get this released!

**Comment by jbaxleyiii** [comment]
Published!

**Comment by johnthepink** [comment]
@Coobaha beautiful!

**Pull request merged**
